version: "3"

volumes:
  mongo_data:

services:
  mongodb:
    image: mongo:4-bionic
    restart: always
    volumes:
      - 'mongo_data:/data/db'
  backend:
    build:
      context: backend_IRIS
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      #MONGODB_DATABASE: iris
      #MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend_IRIS
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:3000"
    stdin_open: true
