version: '3.1'

volumes:
  mongo_data:
services:
  mongo:
    image: mongo:4-bionic
    restart: always
    volumes:
      - 'mongo_data:/data/db'
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  frontend:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 5012:5000
    links:
      - backend
    depends_on:
      - backend

